#!/bin/zsh
export PATH=~/bin:~/local/bin:$PATH
export INFOPATH=~/.emacs.d/info
export DOCKER_HOST="tcp://localhost:4242"

if [ -e $HOME/.tmuxinator/scripts/tmuxinator ]; then
    source $HOME/.tmuxinator/scripts/tmuxinator
fi

if [ -e $HOME/.gvm/scripts/gvm ]; then
    source $HOME/.gvm/scripts/gvm
    export GOPATH=$HOME
fi

if [ -e $HOME/.rvm/scripts/rvm ]; then
    source ~/.rvm/scripts/rvm
fi

export PATH=/usr/local/sbin:$PATH
export PATH=~/Library/Python/2.7/bin:$PATH

export EDITOR='vim'


if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
export PYENV_ROOT=/usr/local/var/pyenv
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi
